
# Configuration to make webrobot work

Alias /webrobot.php ${BASE_DIR}/webrobot/webrobot.php
Alias /ssi-wrapper.php ${BASE_DIR}/webrobot/ssi-wrapper.php
Alias /js/editor.js ${BASE_DIR}/webrobot/js/editor.js
Alias /login.php  ${BASE_DIR}/webrobot/oauth/login.php

<Directory ${BASE_DIR}/pages>
    # Allow .htaccess files to override other settings.
    AllowOverride All
    # Explicitly grant access for Apache 2.4+
    Require all granted
    Options +Includes
    AddOutputFilter INCLUDES .html
</Directory>

<Directory ${BASE_DIR}/pages/includes>
    
    # 1. Define a custom handler name and link it to the script
    Action catch-and-wrap /ssi-wrapper.php
    
    # 2. Force this directory to use your custom handler instead of default file-serving
    SetHandler catch-and-wrap
    
    # 3. Tell Apache to pipe the script's output back into the SSI engine
    SetOutputFilter INCLUDES
</Directory>

<Directory ${BASE_DIR}/webrobot>
    # Password protect only the PHP files in the AI editor directory.
    <FilesMatch "webrobot\.php$">
        AuthType Basic
        AuthName "AI Editor - Restricted Area"
        AuthUserFile ${HTPASSWD_PATH}
        Require valid-user
    </FilesMatch>
</Directory>

<Directory ${BASE_DIR}/pages/upload>
    # Disable directory browsing for security.
    Options -Indexes

    # Prevent execution of any scripts.
    <Files "*">
      SetHandler default-handler
    </Files>
</Directory>
