#
#  Virtual host for 
#
#    domain acms.cweb.com.au
#    website acms.cweb.com.au
#
 
<VirtualHost *:80>
   Include /home/www/acms.cweb.com.au/etc/www.conf
</VirtualHost>
<VirtualHost *:443>

   ServerName www.acms.cweb.com.au
   ServerAlias acms.cweb.com.au

   SSLEngine on
   SSLCertificateFile /home/www/acms.cweb.com.au/etc/certificates/www.acms.cweb.com.au/cert.pem
   SSLCertificateKeyFile /home/www/acms.cweb.com.au/etc/certificates/www.acms.cweb.com.au/key.pem
   SSLCertificateChainFile /home/www/acms.cweb.com.au/etc/certificates/www.acms.cweb.com.au/cacert.pem
   Include /home/www/acms.cweb.com.au/etc/www.conf

</VirtualHost>
