   ServerName www.acms.cweb.com.au
   ServerAlias acms.cweb.com.au 
   ProxyTimeout 300
   Timeout 300
   DocumentRoot /home/www/acms.cweb.com.au/pages
   DirectoryIndex index.html
   SetEnv TZ Australia/Sydney
   ErrorLog /home/www/acms.cweb.com.au/var/log/www_error_log
   CustomLog /home/www/acms.cweb.com.au/var/log/www_access_log combined
   #php_flag magic_quotes_gpc off
   #php_value include_path "/home/www/acms.cweb.com.au/lib:/usr/local/lib/php:."
   #php_value auto_prepend_file "header.php"

<Directory /home/www/acms.cweb.com.au/pages>
    # Allow .htaccess files to override other settings.
    AllowOverride All
    Options +Includes
    AddOutputFilter INCLUDES .html

    # Password protect the AI editor API.
    <FilesMatch "^(api\.php)$">
        AuthType Basic
        AuthName "AI Editor - Restricted Area"
        AuthUserFile /home/ec2-user/etc/htpasswd
        Require valid-user
    </FilesMatch>
</Directory>
